name: Build OpenVM

on:
  workflow_call:
    inputs:
      commit_hash:
        required: true
        type: string
    outputs:
      artifact_name:
        value: ${{ jobs.build.outputs.artifact }}
      build_status:
        value: ${{ jobs.build.outputs.status }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.artifact.outputs.name }}
      status: ${{ steps.status.outputs.value }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build OpenVM Docker Image with Caching
        run: |
          echo "Building Docker image for openvm at commit ${{ inputs.commit_hash }}..."
          docker build \
            --build-arg REPO_URL="https://github.com/codygunton/openvm" \
            --build-arg COMMIT_HASH="${{ inputs.commit_hash }}" \
            -t "zkvm-build-openvm:${{ inputs.commit_hash }}" \
            docker/build-openvm
          
      - name: Extract OpenVM Binary from Docker
        run: |
          echo "Extracting openvm binary from Docker image..."
          mkdir -p artifacts/binaries
          docker run --rm \
            -v "$(pwd)/artifacts/binaries:/output" \
            "zkvm-build-openvm:${{ inputs.commit_hash }}"
          
      - name: Verify Binary
        run: |
          if [ ! -f "artifacts/binaries/cargo-openvm" ]; then
            echo "Error: Expected binary not found at artifacts/binaries/cargo-openvm"
            exit 1
          fi
          echo "Binary found at artifacts/binaries/cargo-openvm"
          ls -la artifacts/binaries/cargo-openvm
          # Rename for artifact upload (force overwrite)
          mv -f artifacts/binaries/cargo-openvm artifacts/binaries/openvm-binary
          
      - name: Upload Binary Artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: openvm-binary-${{ inputs.commit_hash }}
          path: artifacts/binaries/openvm-binary
          retention-days: 7
          
      - name: Set Status Output
        id: status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "value=success" >> $GITHUB_OUTPUT
          else
            echo "value=failure" >> $GITHUB_OUTPUT
          fi