name: Nightly Jolt ZKVM Update

on:
  schedule:
    # Run daily at 3:00 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual trigger for testing

permissions:
  contents: write
  actions: read
  issues: write

concurrency:
  group: jolt-update
  cancel-in-progress: true

jobs:
  update-jolt:
    uses: ./.github/workflows/build-and-test-zkvm.yml
    with:
      zkvm: jolt
